all:
	gcc attacks.c bitboards.c board.c data.c evaluate.c hashkeys.c history.c init.c io.c main.c makemove.c misc.c movegen.c movepicker.c perft.c pvtable.c recog.c search.c see.c tt_eval.c uci.c validate.c -o GOOBv1_8_9 -O3
